version: '3.8'

services:
  # 🤖 Основной сервис копировщика
  copier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-post-copier
    restart: unless-stopped
    
    # Переменные окружения из файла
    env_file:
      - .env
    
    # Volumes для персистентности
    volumes:
      # Весь рабочий каталог (для session файлов и данных)
      - .:/app
      # Альтернативный вариант (если нужна изоляция):
      # - ./copier_session.session:/app/copier_session.session
      # - ./logs:/app/logs
      # - ./temp:/app/temp
      # - ./processed_images:/app/processed_images
    
    # Права пользователя (соответствует пользователю в Dockerfile)
    user: "1000:1000"
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # Сетевые настройки
    networks:
      - telegram-network

networks:
  telegram-network:
    driver: bridge

